### ISSUE TITLE
Problem creating task

### ISSUE THREAD

**Issue by jconlon** [DataReply/kafka-connect-elastic-search-sink#1]
Experimenting in standalone mode with the connector but am seeing the following errors. 

```
[2016-03-12 17:48:19,758] INFO Creating task elasticsearch-schema-sink-0 (org.apache.kafka.connect.runtime.Worker:256)
[2016-03-12 17:48:19,762] INFO Instantiated task elasticsearch-schema-sink-0 with version 0.9.0.0 of type org.apache.kafka.connect.elasticsearchschema.ElasticsearchSinkTask (org.apache.kafka.connect.runtime.Worker:267)
[2016-03-12 17:48:19,763] ERROR Failed to add task elasticsearch-schema-sink-0:  (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:224)
java.lang.ClassCastException: Non-string value found in original settings
    at org.apache.kafka.common.config.AbstractConfig.originalsStrings(AbstractConfig.java:128)
    at org.apache.kafka.connect.runtime.Worker.addTask(Worker.java:288)
    at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.createConnectorTasks(StandaloneHerder.java:222)
    at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.updateConnectorTasks(StandaloneHerder.java:254)
    at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:146)
    at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:85)
[2016-03-12 17:48:19,766] INFO Created connector elasticsearch-schema-sink (org.apache.kafka.connect.cli.ConnectStandalone:82)
[2016-03-12 17:48:19,778] INFO Source task Thread[WorkerSourceTask-verticon-im-source-0,5,main] finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:342)
```

Here is my configuration:

```
name=elasticsearch-schema-sink
connector.class=org.apache.kafka.connect.elasticsearchschema.ElasticsearchSinkConnector
tasks.max=1
topics=com.verticon.im.avro.ObserveEvent
elasticsearch.cluster.name=elasticsearch
elasticsearch.hosts=localhost:9300
# TODO
elasticsearch.index.prefix=prefix
#TODO
elasticsearch.document.name=ObserveEvent
elasticsearch.bulk.size=10
#TODO
elasticsearch.indexes=Verticon-IM
```

Any ideas of what might be causing this?  

thanks for any help,
John

**Comment by patelliandrea** [comment]
Yeah sorry, I've added the optional configuration `date.format` used to append to the index the current date in the format supplied with the configuration (e.g. if you want to write documents on different indexes on a daily basis) and forgot to check for null values.

The last [commit](https://github.com/DataReply/kafka-connect-elastic-search-sink/commit/2caf86d7359c01570949e2c1fcb6a479e254423e) should solve the problem.

**Comment by jconlon** [comment]
Thanks for the quick response...

Added the dateFormat property to my config and got past that problem **but ran into another**.  

So I simplified my set up to  just use the topic generated from the kafka connect-file-source 

## Run command

`/confluent-2.0.1$ ./bin/connect-standalone ./etc/schema-registry/connect-avro-standalone.properties ./etc/kafka/connect-file-source.properties ./etc/kafka/connect-console-sink.properties ./etc/kafka-connect-elastic-search-sink/connect-elasticsearch-schema-sink.properties
`

## Configuration

```
name=elasticsearch-schema-sink
connector.class=org.apache.kafka.connect.elasticsearchschema.ElasticsearchSinkConnector
tasks.max=1
#topics=com.verticon.im.avro.ObserveEvent
topics=connect-test
elasticsearch.cluster.name=elasticsearch
elasticsearch.hosts=localhost:9300
# TODO
elasticsearch.index.prefix=prefix
#TODO
#elasticsearch.document.name=ObserveEvent
elasticsearch.document.name=testDocument
elasticsearch.bulk.size=10
#TODO
elasticsearch.indexes=Verticon-Test
date.format=yyyy-mm-dd
```

## Log snippet with error

```
[2016-03-13 11:43:25,036] INFO Creating task elasticsearch-schema-sink-0 (org.apache.kafka.connect.runtime.Worker:256)
[2016-03-13 11:43:25,037] INFO Instantiated task elasticsearch-schema-sink-0 with version 0.9.0.0 of type org.apache.kafka.connect.elasticsearchschema.ElasticsearchSinkTask (org.apache.kafka.connect.runtime.Worker:267)
[2016-03-13 11:43:25,037] INFO ConsumerConfig values: 
    metric.reporters = []
    metadata.max.age.ms = 300000
    value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
    group.id = connect-elasticsearch-schema-sink
    partition.assignment.strategy = [org.apache.kafka.clients.consumer.RangeAssignor]
    reconnect.backoff.ms = 50
    sasl.kerberos.ticket.renew.window.factor = 0.8
    max.partition.fetch.bytes = 1048576
    bootstrap.servers = [localhost:9092]
    retry.backoff.ms = 100
    sasl.kerberos.kinit.cmd = /usr/bin/kinit
    sasl.kerberos.service.name = null
    sasl.kerberos.ticket.renew.jitter = 0.05
    ssl.keystore.type = JKS
    ssl.trustmanager.algorithm = PKIX
    enable.auto.commit = false
    ssl.key.password = null
    fetch.max.wait.ms = 500
    sasl.kerberos.min.time.before.relogin = 60000
    connections.max.idle.ms = 540000
    ssl.truststore.password = null
    session.timeout.ms = 30000
    metrics.num.samples = 2
    client.id = 
    ssl.endpoint.identification.algorithm = null
    key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
    ssl.protocol = TLS
    check.crcs = true
    request.timeout.ms = 40000
    ssl.provider = null
    ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
    ssl.keystore.location = null
    heartbeat.interval.ms = 3000
    auto.commit.interval.ms = 5000
    receive.buffer.bytes = 32768
    ssl.cipher.suites = null
    ssl.truststore.type = JKS
    security.protocol = PLAINTEXT
    ssl.truststore.location = null
    ssl.keystore.password = null
    ssl.keymanager.algorithm = SunX509
    metrics.sample.window.ms = 30000
    fetch.min.bytes = 1024
    send.buffer.bytes = 131072
    auto.offset.reset = earliest
 (org.apache.kafka.clients.consumer.ConsumerConfig:165)
[2016-03-13 11:43:25,042] INFO Kafka version : 0.9.0.0 (org.apache.kafka.common.utils.AppInfoParser:82)
[2016-03-13 11:43:25,042] INFO Kafka commitId : fc7243c2af4b2b4a (org.apache.kafka.common.utils.AppInfoParser:83)
[2016-03-13 11:43:25,045] INFO Created connector elasticsearch-schema-sink (org.apache.kafka.connect.cli.ConnectStandalone:82)
[2016-03-13 11:43:25,313] INFO [Empathoid] loaded [], sites [] (org.elasticsearch.plugins:153)
[2016-03-13 11:43:25,857] ERROR Thread WorkerSinkTask-elasticsearch-schema-sink-0 exiting with uncaught exception:  (org.apache.kafka.connect.util.ShutdownableThread:84)
java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: newWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function
    at org.elasticsearch.transport.netty.NettyTransport.createClientBootstrap(NettyTransport.java:320)
    at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:248)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.transport.TransportService.doStart(TransportService.java:170)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:148)
    at org.apache.kafka.connect.elasticsearchschema.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:91)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.joinConsumerGroupAndStart(WorkerSinkTask.java:154)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:54)
    at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Exception in thread "WorkerSinkTask-elasticsearch-schema-sink-0" java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: newWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function
    at org.elasticsearch.transport.netty.NettyTransport.createClientBootstrap(NettyTransport.java:320)
    at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:248)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.transport.TransportService.doStart(TransportService.java:170)
    at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
    at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:148)
    at org.apache.kafka.connect.elasticsearchschema.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:91)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.joinConsumerGroupAndStart(WorkerSinkTask.java:154)
    at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:54)
    at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
[2016-03-13 11:43:44,762] INFO Sink task org.apache.kafka.connect.runtime.WorkerSinkTask@7eed8cc4 finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:155)

```

## Other tweaks

Looked like a protocol mismatch with Elasticsearch ( I was using 1.7.2), so I tried 1.7.3 and 2.2.0 but had the same problem

Any ideas?

**Comment by patelliandrea** [comment]
Looks like you have two different versions of netty on your classpath, one from the connector jar and one from another jar. (http://stackoverflow.com/questions/35539535/elasticsearch-cant-get-the-transportclient-when-connect-the-local-env)

**Comment by jconlon** [comment]
Yes, I now see that is the problem, but how to fix it?  I do not set my classpath prior to running the standalone kafka-connect and am using the standard **confluent-2.0.1** distribution so my classpath ends up being:

`:./bin/../share/java/confluent-common/*:./bin/../share/java/kafka-serde-tools/*:./bin/../share/java/kafka-connect-elastic-search-sink/*:./bin/../share/java/kafka-connect-hdfs/*:./bin/../share/java/kafka-connect-jdbc/*`

How did you get yours running as a standalone?

**Comment by jconlon** [comment]
To fix the netty duplicates I removed:

Then I got the following exception:

```
[2016-03-14 12:42:20,073] INFO [Peace Monger] failed to get node info for {#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}, disconnecting... (org.elasticsearch.client.transport:373)
RemoteTransportException[[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]]; nested: TransportSerializationException[Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.liveness.LivenessResponse]]; nested: ExceptionInInitializerError; nested: IllegalArgumentException[An SPI class of type org.apache.lucene.codecs.PostingsFormat with name 'Lucene50' does not exist.  You need to add the corresponding JAR file supporting this SPI to your classpath.  The current classpath supports the following names: [es090, completion090, XBloomFilter]];
```

Which I suspected was caused by a mismatch on ES versions,  I am running ES 2.2 your connector was using 2.0.0.   So I boosted the ES dep on the connector to 2.2.0:

```
<artifactId>elasticsearch</artifactId>
            <version>2.2.0</version>
```

and rebuilt and deployed the jar & deps jar to the tree.  

Was able to get this working with the avro example in the confluent getting started but I am getting Connection problems which appear to be related to Avro deserializatrion with my production payloads which work ok with the ./bin/kafka-avro-console-consumer.  

[Seems to be a confluent avro issue](https://groups.google.com/forum/#!topic/confluent-platform/VLXLtSpx5cw), but I will report back as to the resolution.

**Comment by jconlon** [comment]
## Problem Resolution

It was a two step process to get it working.  First was my screw up.  The second a bug in the Confluent connect mapping from avro.

### 1. Need to set both key and value serializers

 This one was my issue -  I set the 

```
props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
          io.confluent.kafka.serializers.KafkaAvroSerializer.class);
```

but was not setting:

```
props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,
          io.confluent.kafka.serializers.KafkaAvroSerializer.class);
```

### 2. Avro to Kafka Connect - Null Strings in Avro records

The next problem I ran into was really a Confluent issue:

 [NullPointerException when using Avro converter #272](https://github.com/confluentinc/schema-registry/issues/272)

I worked around it by setting my String values to "".

**Comment by vishwastyagi** [comment]
I am getting following exception while starting elasticsearch:

[2016-08-12 14:06:16,659][INFO ][node                     ] [Elaine Grey] version[2.3.4], pid[27475], build[e455fd0/2016-06-30T11:24:31Z]
[2016-08-12 14:06:16,660][INFO ][node                     ] [Elaine Grey] initializing ...
Exception in thread "main" java.lang.ClassCastException: class com.elastic.plugin.ElasticsearchSinkConnector
    at java.lang.Class.asSubclass(Class.java:3404)
    at org.elasticsearch.plugins.PluginsService.loadPluginClass(PluginsService.java:463)
    at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:431)
    at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
    at org.elasticsearch.node.Node.<init>(Node.java:158)
    at org.elasticsearch.node.Node.<init>(Node.java:140)
    at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
    at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
    at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

ElasticsearchSinkConnector class is a public class and extends org.apache.kafka.connect.sink.SinkConnector
Please suggest some solution for this problem.
